language: python

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge

  # Useful for debugging any issues with conda
  - conda info -a

  # Install mamba to make the build run faster later
  - conda install -c conda-forge mamba

  # Install Python, py.test, and required packages.
  - mamba env create -f environment.yml
  - source activate essays-on-data-science
  - python -m ipykernel install --name essays-on-data-science --user

script: true

before_deploy:
  - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: site
  on:
    branch: master

notifications:
  email: true
