# We only want the essentials for building the website.
# Other packages will make the environment bloat too much,
# therefore any notebooks added should preserve their outputs.
name: essays-on-data-science
channels:
- conda-forge
dependencies:
- python=3.7
- pygments=2.4.2
- pre-commit=1.20.0
- pip
- pip:
  - mkdocs-minify-plugin
  - pymdown-extensions
  - mknotebooks
  - mkdocs
  - mkdocs-material
